In [28]:
import tushare as ts

df = ts.get_hist_data("601318", start='2019-06-09', end='2020-06-09')
df
df.to_csv('601318_day_1year.csv')

In [27]:
import tushare as ts

df = ts.get_hist_data("601318", ktype='W', start='2019-06-09', end='2020-06-09')
df
# df.to_csv('601318_week_1year.csv')

# 历史分笔

获取个股以往交易历史的分笔数据明细，通过分析分笔数据，可以大致判断资金的进出情况。在使用过程中，对于获取股票某一阶段的历史分笔数据，需要通过参入交易日参数并append到一个DataFrame或者直接append到本地同一个文件里。历史分笔接口只能获取当前交易日之前的数据，当日分笔历史数据请调用get_today_ticks()接口或者在当日18点后通过本接口获取。

参数说明：

code：股票代码，即6位数字代码

date：日期，格式YYYY-MM-DD

retry_count : int, 默认3,如遇网络等问题重复执行的次数

pause : int, 默认 0,重复请求数据过程中暂停的秒数，防止请求间隔时间太短出现的问题

In [26]:
import tushare as ts

df = ts.get_tick_data('601318',date='2020-06-09',src='tt')
df
# df.to_csv('601318_fenbi_20200609.csv')

http://stock.gtimg.cn/data/index.php?appn=detail&action=download&c=sh601318&d=20200609

          time  price  change  volume    amount type
0     09:25:04  76.73    0.01    4092  31397916   买盘
1     09:30:02  76.73    0.00     468   3598148   买盘
2     09:30:05  76.75    0.02     822   6310450   卖盘
3     09:30:08  76.74   -0.01     199   1527242  中性盘
4     09:30:10  76.73   -0.01     320   2455500   卖盘
...        ...    ...     ...     ...       ...  ...
4709  14:56:52  76.49    0.00      30    229493   卖盘
4710  14:56:54  76.49    0.00     148   1132072   卖盘
4711  14:56:58  76.49    0.00      34    260066   卖盘
4712  14:57:03  76.49    0.00      92    703782   买盘
4713  15:00:01  76.50    0.01    4437  33943050   卖盘

[4714 rows x 6 columns]

返回值说明:

time：时间

rice：成交价格

change：价格变动

volume：成交手

amount：成交金额(元)

type：买卖类型【买盘、卖盘、中性盘

In [12]:
ts.get_k_data("601318", start='2020-05-09', end='2020-06-09')

           date   open  close   high    low    volume    code
82   2020-05-11  73.11  73.90  74.80  73.11  495757.0  601318
83   2020-05-12  73.90  73.93  74.33  73.47  415450.0  601318
84   2020-05-13  73.60  73.34  73.93  72.65  288970.0  601318
85   2020-05-14  73.00  72.23  73.00  72.17  349715.0  601318
86   2020-05-15  72.61  72.23  73.10  72.18  317507.0  601318
87   2020-05-18  72.20  72.20  72.98  71.69  308463.0  601318
88   2020-05-19  73.18  72.90  73.60  72.61  341583.0  601318
89   2020-05-20  73.00  72.95  73.19  72.50  274835.0  601318
90   2020-05-21  73.20  72.38  73.30  72.36  312686.0  601318
91   2020-05-22  72.06  70.12  72.10  70.10  577194.0  601318
92   2020-05-25  70.00  70.03  70.08  69.00  417101.0  601318
93   2020-05-26  70.99  70.51  71.00  70.32  271128.0  601318
94   2020-05-27  70.72  70.65  71.58  70.52  287152.0  601318
95   2020-05-28  70.68  71.51  71.99  70.68  414260.0  601318
96   2020-05-29  70.90  70.71  71.30  70.48  268441.0  601318
97   2020-06-01  71.40  72.16  72.23  71.23  457673.0  601318
98   2020-06-02  72.02  74.28  74.53  72.01  810523.0  601318
99   2020-06-03  75.00  75.01  76.69  75.00  991488.0  601318
100  2020-06-04  75.42  75.14  75.71  74.58  453880.0  601318
101  2020-06-05  75.14  75.30  75.44  74.40  349808.0  601318
102  2020-06-08  75.70  76.72  77.22  75.70  766974.0  601318